- name: copy php-fpm
  template:
    src: templates/php.ini.j2
    dest: "{{ php_ini_dest }}"
    owner: root
    group: root
    mode: '0600'
    backup: yes
  notify:
    - restart php-fpm

- name: copy www.conf
  template:
    src: templates/php74-fpm-www.conf.j2
    dest: "{{ php_fpm_dest }}"
    owner: root
    group: root
    mode: '0600'
    backup: yes
  notify:
    - restart php-fpm