---
- name: Set facts for Debian
  set_fact:
    nginx_user: "www-data"
    php_ini_dest: "/etc/php/7.4/fpm/php.ini"
    php_fpm_dest: "/etc/php/7.4/fpm/pool.d/www.conf"
    php_fpm_service: "php7.4-fpm"
  when: ansible_os_family == "Debian"

- name: Set facts for RedHat
  set_fact:
    nginx_user: "nginx"
    php_ini_dest: "/etc/php.ini"
    php_fpm_dest: "/etc/php-fpm.d/www.conf"
    php_fpm_service: "php-fpm"
  when: ansible_os_family == "RedHat"

- name: Install Red Hat Remi Repository
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
  when: ansible_os_family == "RedHat"

- name: Install ondrej/php Repo for Debian
  apt_repository:
    repo: ppa:ondrej/php
    state: present
  when: ansible_os_family == "Debian"

- name: Install Packages for RedHat
  dnf:
    state: present
    name:
      - '@php:remi-7.4'
      - php-cli
      - php-fpm
      - php-devel
      - php-mysqlnd
      - php-pear
      - php-xml
      - php-pdo
      - php-common
      - php-gd
      - php-mbstring
      - php-intl
      - php-pecl-apcu
      - php-mysqlnd
      - php-opcache
      - php-json
      - php-zip
      - php-redis
      - php-imagick
  when: ansible_os_family == "RedHat"

- name: install Packages for Debian
  apt:
    state: present
    name:
      - php7.4-fpm
      - php7.4-cli
      - php7.4-common
      - php7.4-mysql
      - php7.4-mbstring
      - php7.4-gd
      - php7.4-imagick
      - php7.4-intl
      - php7.4-bz2
      - php7.4-xml
      - php7.4-pgsql
      - php7.4-zip
      - php7.4-dev
      - php7.4-smbclient
      - php7.4-ldap
      - php7.4-curl
  when: ansible_os_family == "Debian"


- name: copy php-fpm
  template:
    src: templates/php.ini.j2
    dest: "{{ php_ini_dest }}"
    owner: root
    group: root
    mode: '0600'
    backup: yes
  notify:
    - restart php-fpm

- name: copy www.conf
  template:
    src: templates/php74-fpm-www.conf.j2
    dest: "{{ php_fpm_dest }}"
    owner: root
    group: root
    mode: '0600'
    backup: yes
  notify:
    - restart php-fpm