---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos-8
    image: geerlingguy/docker-centos8-ansible
    pre_build_image: true
  - name: ubuntu-18.04
    image: geerlingguy/docker-ubuntu1804-ansible
    pre_build_image: true
  - name: ubuntu-20.04
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
  - name: debian-10
    image: geerlingguy/docker-debian10-ansible
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
